gtb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve

from gtb import settings
from .import views

urlpatterns = [

    url('^$', views.start),
    path('Best-Hotel-In-Dubai', views.index, name="index"),
    path('About_Royal_Continental_hotel', views.about, name="aboutpage"),
    path('Best_Room_In_Dubai', views.room, name="roompage"),
    path('signup_Royal_Continental_hotel', views.mysignup.as_view(), name="signpage"),
    path('signout', views.mysignout, name='signout'),
    path('My_Account', views.myaccount, name='myaccount'),
    path('Payment_Page', views.final, name='final'),
    path('contact', views.showcontactus, name='contactus'),
    path('update-profile', views.updateuser, name='updateprofile'),
    path('booking_Royal_Continental_hotel/<int:detailid>', views.mybooking, name="booking"),
    path('login_Royal_Continental_hotel', views.mylogin, name="loginpage"),
    path('Change-Form', views.changepass, name="changepassword"),
    path('Room_Details_Royal_Continental_hotel/<int:catid>', views.RoomDetails, name="myroomdetails"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      views.activate_account, name='activate'),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
   handler400 = 'common.views.bad_request'
   handler403 = 'common.views.permission_denied'
   handler404 = 'common.views.page_not_found'
   handler500 = 'common.views.server_error'

website/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Roomcategory(models.Model):
    categoryname=models.CharField(max_length=30)
    services = RichTextField()
    roomsize=models.CharField(max_length=30)
    beds = models.CharField(max_length=30)
    capcity = models.CharField(max_length=30)
    bedtype = models.CharField(max_length=30)
    roomavailable=models.IntegerField(default=0)
    Image = models.ImageField(upload_to='uploads/%Y/%m/%d/', blank='True', null='True')

    def __str__(self):
        return self.categoryname

class Roomcategorydetails(models.Model):
    roomcategoryid=models.ForeignKey(Roomcategory,on_delete=models.CASCADE)
    roomoption=models.CharField(max_length=200)
    roomprice=models.IntegerField()

    def __str__(self):
        return str(self.roomoption
                   )

class Booking(models.Model):
    userid = models.ForeignKey(User, on_delete=models.CASCADE)
    roomcategoryid = models.ForeignKey(Roomcategory, on_delete=models.CASCADE)
    roomdetailid = models.ForeignKey(Roomcategorydetails, on_delete=models.CASCADE)
    checkindate = models.DateField()
    checkoutdate = models.DateField()
    amount = models.IntegerField()
    totalpersons = models.IntegerField()
    guestname = models.CharField(max_length=70)
    gender_choices = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('Other', 'Other'),
    )
    gender = models.CharField(max_length=6, choices=gender_choices)

    def __str__(self):
        return str(self.userid)



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birth_date = models.DateField(null=True, blank=True)
    phone = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.user)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class register_table(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_pic = models.ImageField(upload_to="profiles/%Y/%m/%d", null=True, blank=True,
                                    default='/staticfiles/images/user.png')

    def __str__(self):
        return self.user.username


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = register_table.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

website/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django import forms
from django.core.mail import EmailMessage
from django.forms import ModelForm
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode

from website.models import Booking,Profile
from website.token_generator import account_activation_token


class signupform(forms.ModelForm):
    username=forms.CharField(label="Username",max_length=100)
    first_name = forms.CharField(label="First Name", max_length=100)
    last_name = forms.CharField(label="Last Name", max_length=100)
    email = forms.CharField(label="Email", max_length=100)
    password1=forms.CharField(label="Password",widget=forms.PasswordInput)
    password2=forms.CharField(label="Confirm password",widget=forms.PasswordInput)


    class Meta:
        model=User
        fields=('username','email','first_name','last_name',)

    def clean_password2(self):
        pass1=self.cleaned_data.get("password1")
        pass2 =self.cleaned_data.get("password2")
        if pass1 and pass2 and pass1 != pass2:
            raise forms.ValidationError("Password does not match or not enterted properly")
        return pass2

    def save(self, commit=True):
        userobj=super(signupform,self).save(commit=False)
        userobj.set_password(self.cleaned_data["password2"])
        userobj.is_active = False
        if commit:
            userobj.save()
            current_site = "jalandharhhotel.herokuapp.com"
            email_subject = 'Activate Your Account'
            message = render_to_string('activate_account.html', {
                'user': userobj,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(userobj.pk)).decode(),
                'token': account_activation_token.make_token(userobj),
            })
            to_email = self.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
        return userobj

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('birth_date', 'phone')


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','first_name','last_name',)

class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        user1 = self.cleaned_data.get("username")
        pass1 = self.cleaned_data.get("password")

        user_obj = authenticate(username=user1, password=pass1)

        if not user_obj:
            raise forms.ValidationError("Wrong username / password or not activated by email")

        return super(LoginForm, self).clean(*args, **kwargs)

class BookingForm(ModelForm):
    class Meta:
        model = Booking
        exclude = ('userid', 'roomcategoryid','roomdetailid','amount')


class ContactForm(forms.Form):
 name = forms.CharField(label="Name")
 emailid = forms.CharField(label="Email ID")
 message = forms.CharField(label="Message", widget=forms.Textarea)

website/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import logout
from django.core.mail import send_mail
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages
import requests
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView

from .forms import signupform, LoginForm, BookingForm, UserForm, ProfileForm, ContactForm
from .models import Roomcategory, Roomcategorydetails, Booking, register_table
from .token_generator import account_activation_token


def start(request):

    return render(request, "startbase.html")

def index(request):
    context = {}
    check = register_table.objects.filter(user__id=request.user.id)
    if len(check) > 0:
        data = register_table.objects.get(user__id=request.user.id)
        context["data"] = data

        if "image" in request.FILES:
            img = request.FILES["image"]
            data.profile_pic = img
            data.save()

    return render(request, "index.html",context)

def final(request):

    return render(request, "final.html")

class mysignup(SuccessMessageMixin,CreateView):
    form_class = signupform
    template_name = 'signup.html'
    success_message = "Your account has been created successfully .Please activiate your account with your email id."
    success_url = reverse_lazy('signpage')

    def dispatch(self, *args, **kwargs):
        return super(mysignup,self).dispatch(*args, **kwargs)

@login_required
def mybooking(request, detailid):
    roomcategoryobj = Roomcategory.objects.get(id=request.session["catid"])
    roomcategorydetailsobj = Roomcategorydetails.objects.get(id=detailid)
    image = roomcategoryobj.Image
    catname = roomcategoryobj.categoryname
    roomoptions = roomcategorydetailsobj.roomoption
    price = roomcategorydetailsobj.roomprice
    details = {"image":image, "catname" :catname, "roomoptions":roomoptions, "price":price}
    formobj = BookingForm(request.POST or None)
    if request.method == "POST":
        if formobj.is_valid():
            data = formobj.save(commit=False)
            categoryid = request.session["catid"]

            case_1 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__lte=data.checkindate,
                                            checkoutdate__gte=data.checkindate).exists()

            # case 2: a room is booked before the requested check_out date and check_out date is after requested
            # check_out date
            case_2 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__lte=data.checkoutdate,
                                            checkoutdate__gte=data.checkoutdate).exists()

            case_3 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__gte=data.checkindate,
                                            checkoutdate__lte=data.checkoutdate).exists()

            # if either of these is true, abort and render the error
            if case_1 or case_2 or case_3:
                count1 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__lte=data.checkindate,
                                            checkoutdate__gte=data.checkindate).count()
                count2 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__lte=data.checkoutdate,
                                            checkoutdate__gte=data.checkoutdate).count()
                count3 = Booking.objects.filter(roomcategoryid=categoryid, checkindate__gte=data.checkindate,
                                            checkoutdate__lte=data.checkoutdate).count()

                totalcount = 0
                if count1 > 0:
                    totalcount += count1
                elif count2 > 0:
                    totalcount += count2
                elif count3 > 0:
                    totalcount += count3

                if totalcount == roomcategoryobj.roomavailable:
                    messages.error(request, 'Selected Dates are not available')
                    return render(request, "booking.html", {"form": formobj})

            data.userid = User(id=request.session["userid"])
            data.roomcategoryid = roomcategoryobj
            data.roomdetailid = Roomcategorydetails(id=detailid)
            checkindate = data.checkindate
            checkoutdate = data.checkoutdate
            daysinfo = checkoutdate - checkindate

            data.amount = roomcategorydetailsobj.roomprice
            totalbill = data.amount * daysinfo.days
            data.save()
            bookingid = data.id
            context = {"bookingid": bookingid, "total": totalbill}
            return render(request, "final.html", context)
            # messages.success(request,
            #                  'Your request for booking has been successful. Your booking id is ' + str(bookingid)
            #                  + ' Your total bill amount is ' + str(totalbill)
            #                  + '. Pay on 8054463693 on Google Pay / Paytm / UPI')
        else:
            formobj = BookingForm(request.POST)
    return render(request, "booking.html", {"form": formobj, "roomdetails":details})



def mylogin(request):
    formobj = LoginForm(request.POST or None)
    redirect_to=request.POST.get('next')
    if formobj.is_valid():
        username = formobj.cleaned_data.get("username")
        userobj = User.objects.get(username__iexact=username)
        login(request, userobj)
        request.session["userid"] = userobj.id
        request.session["myusername"] = userobj.username
        request.session["myuseremail"] = userobj.email
        if redirect_to:
            return redirect(redirect_to)
        else:
            return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "login.html", {"form": formobj})


def about(request):
    url = "http://api.openweathermap.org/data/2.5/weather?q=Jalandhar&appid=d6bf2e65d36627e9c4da4ace08b789e7&units=metric"
    json_data = requests.get(url).json()
    temperature = json_data["main"]["temp"]
    temperature2 = json_data["name"]
    temperature3 = json_data["weather"][0]["main"]
    tempdata = {"temp": temperature, "temp2": temperature2, "temp3": temperature3}

    return render(request, "aboutus.html",tempdata)


def showcontactus(request):
    myform = ContactForm(request.POST or None)
    if myform.is_valid():
        data = request.POST
        name = data.get("name", "0")
        emailid = data.get("emailid", "0")
        message = data.get("message", "0")
        result = send_mail("Message from Website", "Name : " + name + "\nEmailid : " + emailid + "\nMessage : " + message,
            "royalcontinentalhotell@gmail.com", ["royalcontinentalhotell@gmail.com"], fail_silently=False)
        return render(request, "contactus.html", {"form": myform, "status": result})
    else:
        return render(request, "contactus.html", {"form": myform})




def myaccount(request):
    context = {}
    check = register_table.objects.filter(user__id=request.user.id)
    if len(check) > 0:
        data = register_table.objects.get(user__id=request.user.id)
        context["data"] = data

        if "image" in request.FILES:
            img = request.FILES["image"]
            data.profile_pic = img
            data.save()

    return render(request, "myaccount.html", context)

def room(request):
    obj = Roomcategory.objects.all()  # Getting all the records from database
    context = {"roomdetails": obj}
    return render(request, "rooms.html",context)

def RoomDetails(request, catid):
    obj = Roomcategorydetails.objects.select_related('roomcategoryid').filter(roomcategoryid=catid)
    obj2 = Roomcategorydetails.objects.select_related('roomcategoryid').filter(roomcategoryid=catid).first()
    request.session["catid"]=catid
    context = {"roomcategorydetails": obj, "roomcatdetails": obj2}
    return render(request, "roomdetails.html", context)

@login_required
def changepass(request):
    if request.method == 'POST':
        data = request.POST
        oldpassword = data.get("oldpassword", "1")
        password1 = data.get("password1", "0")
        password2 = data.get("password2", "0")
        if password1 == password2:
            myusername = request.session["myusername"]
            userobj = authenticate(username=myusername, password=oldpassword)
            if userobj:
                userobj.set_password(password1)
                userobj.save()
                logout(request)
                formobj = LoginForm(None)
                context = {"form": formobj, "loginmessage": "done"}
                return render(request, "login.html", context)
            else:
                context = {"mymessage": "Wrong old password"}
        else:
            context = {"mymessage": "New Passwords does not match"}
        return render(request, "changepassword.html", context)
    else:
        return render(request, "changepassword.html")

def mysignout(request):
    if request.session.has_key("myusername"):
        del request.session["myusername"]
        logout(request)
    return HttpResponseRedirect(reverse("index"))

@login_required
@transaction.atomic
def updateuser(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile was successfully updated!')

        else:

website/templates/aboutus.html
{% extends user.is_authenticated|yesno:"userbase.html,base.html" %}
{% load static %}
{% block title %} About Us {% endblock %}


{% block content %}
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <style type="text/css">



.hello1{
    overflow: hidden;
    z-index: 10;
    position: relative;
    margin: 150px auto;
    height: 90px;
    width: 300px;
    background-color: #F17022;
    border-radius: 10px;
    box-shadow: 2px 2px 1px rgba(0,0,0,0.2);
    margin-top: 20px;

}


/*  BACKGROUND  */

.Circle1{
    z-index: 100;
    position: absolute;
    height: 80px;
    width: 80px;
    right: -20px;
    top: -30px;
    border-radius: 50%;
    background-color: rgba(253,184,19,1);
    animation: enlarge;
    animation-duration: 5s;
    animation-iteration-count: infinite;
}

.Circle2{
    z-index: 80;
    position: absolute;
    height: 150px;
    width: 150px;
    right: -50px;
    top: -70px;
    border-radius: 50%;
    background-color: rgba(246,140,31,0.7);

    animation: enlarge;
    animation-duration: 7s;
    animation-iteration-count: infinite;
}

.Circle3{
    z-index: 50;
    position: absolute;
    height: 200px;
    width: 200px;
    right: -50px;
    top: -100px;
    border-radius: 50%;
    background-color: rgba(241,125,45,0.7);

    animation: enlarge;
    animation-duration: 10s;
    animation-iteration-count: infinite;
}



/*  CONTENT  */

.sun{
    z-index: 1000;
    font-size: 15px !important;
}

.Condition{
    z-index: 1000;
    position: absolute;
    font-family: "Roboto", sans-serif;
    font-weight: 100;
    font-size: 20px;
    left: 20px;
    top: 10px;
    margin-top: 3px;
}

.Temp{
    z-index: 1000;
    position: absolute;
    font-family: "Roboto", sans-serif;
    font-size: 30px;
    font-weight: 400;
    left: 20px;
    bottom: 5px;
    margin-bottom: 7px;
}

#F{
    z-index: 1000;
    font-family: "Roboto",sans-serif;
    font-weight: 100;
    font-size: 30px;
}


.Time{
    z-index: 1000;
    position: absolute;
    font-family: "Noto Sans", sans-serif;
    font-size: 18px;
    font-weight: 200;
    right: 20px;
    top: 10px;
}

.locationIcon{
    z-index: 1000;
    font-size: 10px !important;
}

.Location{
    z-index: 1000;
    position: absolute;
    font-family: "Noto Sans", sans-serif;
    font-size: 12px;
    font-weight: 200;
    right: 20px;
    bottom: 15px;
}

@keyframes enlarge{
    50%{
        transform: scale(1.2);
    }
}
  </style>

<!-- Breadcrumb Section Begin -->

        <div class="container">
            <div class="row">
                <div class="col-lg-9">
                    <div class="breadcrumb-text" style="margin-top:30px;">
                        <h2>About Us</h2>
                        <div class="bt-option">
                            <a href="{% url 'index' %}">Home</a>
                            <span>About Us</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3">
                    	<div class="hello1">
                          <div class="background">
                          <div class="Circle1"></div>
                          <div class="Circle2"></div>
                          <div class="Circle3"></div>
                          <div class="hello">
                            <h1 class="Condition"><i class="material-icons sun">wb_sunny</i> {{ temp3 }}</h1>
                            <h1 class="Temp">{{ temp }}<span id="F">&#8451;</span></h1>
                            <h1 class="Time">16:35</h1>
                            <h1 class="Location"><i class="material-icons locationIcon">place</i> {{ temp2 }}</h1>
                          </div>
                            </div>

		                </div>

                </div>

            </div>
        </div>

    <!-- Breadcrumb Section End -->

    <!-- About Us Page Section Begin -->
    <section class="aboutus-page-section spad">
        <div class="container">
            <div class="about-page-text">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="ap-title">
                            <h2>Welcome To Jalandhar Continental Hotel </h2>
                            <p>Built in 1910 during the Belle Epoque period, this hotel is located in the center of
                                Paris, with easy access to the city’s tourist attractions. It offers tastefully
                                decorated rooms.</p>
                        </div>
                    </div>
                    <div class="col-lg-5 offset-lg-1">
                        <ul class="ap-services">
                            <li><i class="icon_check"></i> 20% Off On Accommodation.</li>
                            <li><i class="icon_check"></i> Complimentary Daily Breakfast</li>
                            <li><i class="icon_check"></i> 3 Pcs Laundry Per Day</li>
                            <li><i class="icon_check"></i> Free Wifi.</li>
                            <li><i class="icon_check"></i> Discount 20% On F&B</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="about-page-services">
                <div class="row">
                    <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/about-p1.jpg' %}">
                            <div class="api-text">
                                <h3>Restaurants Services</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/about-p2.jpg' %}">
                            <div class="api-text">
                                <h3>Travel & Camping</h3>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="ap-service-item set-bg" data-setbg="{% static 'img/about/about-p3.jpg' %}">
                            <div class="api-text">
                                <h3>Event & Party</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Us Page Section End -->

    <!-- Video Section Begin -->
    <section class="video-section set-bg" data-setbg="{% static 'img/video-bg.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="video-text">
                        <h2>Discover Our Hotel & Services.</h2>
                        <p>It S Hurricane Season But We Are Visiting Hilton Head Island</p>
                        <a href="https://www.youtube.com/watch?v=EzKkl64rRbM" class="play-btn video-popup"><img
                                src="{% static 'img/play.png' %}" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Video Section End -->

    <!-- Gallery Section Begin -->
    <section class="gallery-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Our Gallery</span>
                        <h2>Discover Our Work</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/gallery-1.jpg' %}">
                        <div class="gi-text">
                            <h3>Standard Rooms</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/gallery-3.jpg' %}">
                                <div class="gi-text">
                                    <h3>Delux Rooms</h3>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="gallery-item set-bg" data-setbg="{% static 'img/gallery/gallery-4.jpg' %}">
                                <div class="gi-text">
                                    <h3>Premium Rooms</h3>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="gallery-item large-item set-bg" data-setbg="{% static 'img/gallery/gallery-2.jpg' %}">
                        <div class="gi-text">
                            <h3>Famiy Suite</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Gallery Section End -->






{% endblock %}

website/templates/activate_account.html
{% autoescape off %}

Hi {{ user.username }},

Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

website/templates/updateprofile.html
{% extends user.is_authenticated|yesno:"userbase.html,base.html" %}
{% load static %}
{% block title %} Update Your Profile {% endblock %}


{% block content %}
<style>
input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=email], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}

input[type=submit] {
  width: 25%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
input[type=reset] {
  width: 25%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}


		@import url('https://fonts.googleapis.com/css?family=Raleway:200');


#box {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 500px;
  height: 150px;
  color: white;
  font-family: 'Raleway';
  font-size: 2.5rem;
  margin-left:500px;
}
.gradient-border {
  --borderWidth: 3px;

  position: relative;
  border-radius: var(--borderWidth);
}
.gradient-border:after {
  content: '';
  position: absolute;
  top: calc(-1 * var(--borderWidth));
  left: calc(-1 * var(--borderWidth));
  height: calc(100% + var(--borderWidth) * 2);
  width: calc(100% + var(--borderWidth) * 2);
  background: linear-gradient(60deg, #f79533, #f37055, #ef4e7b, #a166ab, #5073b8, #1098ad, #07b39b, #6fba82);
  border-radius: calc(2 * var(--borderWidth));
  z-index: -1;
  animation: animatedgradient 3s ease alternate infinite;
  background-size: 300% 300%;
}


@keyframes animatedgradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
.ui-datepicker {
width: 21em; /*what ever width you want*/
}
</style>
<div class="gradient-border" id="box">
	<h2>Update Profile</h2>
</div>
<div class="content">
			<div class="about-section">
				<div class="container">

					<div class="about-grids">
						<div class="col-md-4 about-grid">

							<form action="#" method="post">
								  {% csrf_token %}
							{{ user_form.as_p }}
							{{ profile_form.as_p }} <br>
							<input type="submit" value="Submit">
							<input type="reset" value="Clear" > <br>
							</form>
							<br>

							{% if messages %}
							<ul>
								{% for message in messages %}
									<li>{{ message }}</li>
								{% endfor %}
							</ul>
							{% endif %}
						</div>
						<div class="col-md-8 about-grid">
							<div class="about-top">

								<div class="clearfix"></div>
							</div>


						</div>
						<div class="clearfix"></div>
					</div>
				</div>
			</div>

</div>


  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


<script type="text/javascript">
	$( function() {
    $( "#id_birth_date" ).datepicker({

  	dateFormat: 'yy-mm-dd',

  	});
  	});



</script>
	<!--//team-->
{% endblock %}